[package]
name = "afag_r_project_2"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8",features = ["blocking", "json"] }
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.0"
rusqlite = "0.32.1"


[[bin]]
name = "afag_r_project_2"
path = "src/main.rs"